package com.niftydirection.agent;

import android.content.Context;import android.graphics.*;import android.net.Uri;import android.util.Base64;
import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.text.SimpleDateFormat;import java.util.*;import java.util.List;

public final class OpenAiAnalyzer{
    private OpenAiAnalyzer(){}
    public static String analyze(Context c,Uri uri,String key,String model,String prior)throws Exception{
        String img=encode(c,uri);List<NewsFetcher.NewsItem> news=NewsFetcher.fetchTopNews();String prompt=prompt(news,prior);
        JSONObject body=new JSONObject().put("model",model).put("input",new JSONArray().put(new JSONObject().put("role","user").put("content",new JSONArray()
            .put(new JSONObject().put("type","input_text").put("text",prompt)).put(new JSONObject().put("type","input_image").put("image_url",img)))));
        HttpURLConnection con=(HttpURLConnection)new URL("https://api.openai.com/v1/responses").openConnection();con.setConnectTimeout(15000);con.setReadTimeout(60000);con.setRequestMethod("POST");con.setDoOutput(true);con.setRequestProperty("Authorization","Bearer "+key);con.setRequestProperty("Content-Type","application/json");
        byte[] payload=body.toString().getBytes(StandardCharsets.UTF_8);con.setFixedLengthStreamingMode(payload.length);try(OutputStream o=con.getOutputStream()){o.write(payload);}
        int code=con.getResponseCode();String response=read(code>=200&&code<300?con.getInputStream():con.getErrorStream());con.disconnect();if(code<200||code>=300)throw new IllegalStateException("OpenAI API error "+code+": "+response);
        String text=extract(new JSONObject(response));if(text==null||text.trim().isEmpty())throw new IllegalStateException("The model returned no analysis text.");return text.trim();
    }
    private static String encode(Context c,Uri u)throws Exception{Bitmap original;try(InputStream in=c.getContentResolver().openInputStream(u)){original=BitmapFactory.decodeStream(in);}if(original==null)throw new IllegalArgumentException("Could not decode screenshot.");int max=1600;Bitmap scaled=original;if(original.getWidth()>max)scaled=Bitmap.createScaledBitmap(original,max,(int)Math.round(original.getHeight()*(max/(double)original.getWidth())),true);ByteArrayOutputStream b=new ByteArrayOutputStream();scaled.compress(Bitmap.CompressFormat.JPEG,78,b);if(scaled!=original)scaled.recycle();original.recycle();return "data:image/jpeg;base64,"+Base64.encodeToString(b.toByteArray(),Base64.NO_WRAP);}
    private static String prompt(List<NewsFetcher.NewsItem> ns,String prior){StringBuilder n=new StringBuilder();int i=1;for(NewsFetcher.NewsItem x:ns)n.append(i++).append(". ").append(x.title).append(x.source==null?"":" ["+x.source+"]").append(x.pubDate==null?"":" — "+x.pubDate).append("\n");
        return "You are NIFTY OI + NEWS DIRECTION AGENT. Analyze the uploaded NSE NIFTY option-chain screenshot. Never invent unreadable numbers. Compare prior snapshots. Use Call/Put OI, change OI, volume, IV, LTP/change, spot, support/resistance and sequential changes. Do not use OI alone. Separate screenshot facts from inference. News is context, not proof of causality. Return ONLY valid JSON with keys: direction (BULLISH|BEARISH|RANGE|NEUTRAL|UNCLEAR), confidence (0-100), market_state, spot, pivot, support(array), resistance(array), option_chain_evidence(array), price_momentum, snapshot_change(array), news_impact(POSITIVE|NEGATIVE|MIXED|NEUTRAL|UNKNOWN), news_summary(array), bullish_confirmation(array), bearish_confirmation(array), invalidation(array), false_signal_risk(array), status(WAIT|BULLISH BIAS|BEARISH BIAS|RANGE), risk_notes(array). Confidence is evidence strength, not win probability; require price confirmation when signals conflict.\n\nPRIOR SNAPSHOT HISTORY:\n"+prior+"\n\nCURRENT MARKET NEWS:\n"+n;}
    private static String extract(JSONObject r){JSONArray o=r.optJSONArray("output");if(o==null)return null;StringBuilder s=new StringBuilder();for(int i=0;i<o.length();i++){JSONObject item=o.optJSONObject(i);if(item==null)continue;JSONArray c=item.optJSONArray("content");if(c==null)continue;for(int j=0;j<c.length();j++){JSONObject p=c.optJSONObject(j);if(p!=null&&"output_text".equals(p.optString("type")))s.append(p.optString("text",""));}}return s.length()==0?null:s.toString();}
    private static String read(InputStream in)throws Exception{if(in==null)return "";ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)o.write(b,0,n);return o.toString(StandardCharsets.UTF_8.name());}
}
